NativeAppBase: Enable/disable default hotkeys
DiligentGraphics/DiligentTools pull request #192
Opened 2023-04-08 07:41 UTC by snaulX

Create AppBase::EnableHotkeys() method to enable/disable default hotkeys (such as exit from app on Esc and change fullscreen mode on Shift+Enter in UWP).

2023-04-09 01:47 UTC, TheMostDiligent commented on NativeApp/src/UWP/App.cpp
> +        return;
This will disable handling the shift key

2023-04-09 01:52 UTC, TheMostDiligent commented
This implementation seems to result in incorrect handling of the shift key in UWP. Also, toggling all hot keys on/off at the same time is not very flexible.

I would recommend reworking this change as follows:
- Add `HOT_KEY_FLAGS` flag enum with `HOT_KEY_FLAG_ALLOW_EXIT_ON_ESC` and `HOT_KEY_FLAG_ALLOW_FULL_SCREEN_SWITCH` values.
- Add `HOT_KEY_FLAGS GetHotKeyFlags()` method instead of `EnableHotkeys()`

2023-04-09 13:12 UTC, snaulX commented
Hmm.. Nice idea. Maybe also add `HOT_KEY_FLAG_NONE = 0` (or `HOT_KEY_FLAG_ALLOW_NONE`)?

2023-04-10 06:47 UTC, TheMostDiligent requested changes

2023-04-10 06:47 UTC, TheMostDiligent commented on NativeApp/include/AppBase.hpp
> +        /// App wil change fullscreen mode on Shift+Enter (only in UWP)
Typo: wil

2023-04-10 06:47 UTC, TheMostDiligent commented on NativeApp/include/AppBase.hpp
> +        HOT_KEY_FLAG_ALLOW_EXIT_ON_ESC = 1,
Please use `1 << 0` for consistency

2023-04-10 06:47 UTC, TheMostDiligent commented on NativeApp/include/AppBase.hpp
> +    };
Please add the `HOT_KEY_FLAG_ALL = ~0u` value.

Please add the `DEFINE_FLAG_ENUM_OPERATORS` macro, see example [here](DEFINE_FLAG_ENUM_OPERATORS).

2023-04-10 06:47 UTC, TheMostDiligent commented on NativeApp/include/AppBase.hpp
> +        return HOT_KEY_FLAG_ALLOW_EXIT_ON_ESC | HOT_KEY_FLAG_ALLOW_FULL_SCREEN_SWITCH;
Please return the `HOT_KEY_FLAG_ALL` here. If new enum values are add, it is almost guaranteed that this function will not be updated.

2023-04-10 06:47 UTC, TheMostDiligent commented on NativeApp/src/Linux/LinuxMain.cpp
> +        if (EscPressed && TheApp->GetHotKeyFlags() & HOT_KEY_FLAG_ALLOW_EXIT_ON_ESC)
Please use parens to group bitwise &

2023-04-10 06:47 UTC, TheMostDiligent commented on NativeApp/src/Win32/WinMain.cpp
> +            if (wParam == VK_ESCAPE && g_pTheApp->GetHotKeyFlags() & HOT_KEY_FLAG_ALLOW_EXIT_ON_ESC)
Please use parens to group bitwise &

2023-04-11 19:05 UTC, merged